using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
public float moveSpeed;
public float jumpHeight;
public KeyCode Spacebar;
public KeyCode L;
public KeyCode R;
public Transform groundCheck;
public float groundCheckRadius;
private bool grounded;
public LayerMask whatIsGround;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKey(L)){

             GetComponent<Rigidbody2D>().velocity = new Vector2(-moveSpeed,GetComponent<Rigidbody2D>().velocity.y);


if(GetComponent<SpriteRenderer>()!=null){
    GetComponent<SpriteRenderer>().flipX = true;
}
        }
 if (Input.GetKey(R)){
            
             GetComponent<Rigidbody2D>().velocity = new Vector2(moveSpeed,GetComponent<Rigidbody2D>().velocity.y);

if(GetComponent<SpriteRenderer>()!=null){
    GetComponent<SpriteRenderer>().flipX = false;
}
        }

if (Input.GetKeyDown(Spacebar)&&grounded){
            
            jump();

        }









        void jump(){

              GetComponent<Rigidbody2D>().velocity = new Vector2(GetComponent<Rigidbody2D>().velocity.x,jumpHeight);

        }
    }

void Fixedupdate(){
    grounded = Physics2D.OverlapCircle(groundCheck.position,groundCheckRadius,whatIsGround);
}

}
